In [1]:
import pyvista as pv
import numpy as np

In [11]:
data = np.load("Finite_Element_Mesh.npz") # coordinates, membrane, edge, support, truss
# data.keys()

In [ ]:
coordinates = data['coordinates'] # (349, 4) # 349 nodes with x,y,z

membrane = data['membrane']       # (616, 4) # triangular vertices/ nodes 

edge = data['edge']               # (68, 3)
support = data['support']         # (4, 3)
truss = data['truss']             # (2, 3)

# for name in ['coordinates', 'membrane', 'edge', 'support', 'truss']:
#    print(name, data[name].shape)

In [31]:
print(coordinates[:5])
print(membrane[:5])
print(edge[:5])
print(support[:5])
print(truss[:5])


[[0.       9.       6.       3.      ]
 [1.       5.5      5.5      3.      ]
 [2.       5.67681  4.97373  0.555021]
 [3.       5.60052  4.63018  0.728469]
 [4.       5.76836  5.31632  0.376306]]
[[  1 346 345 344]
 [  2 292 290 275]
 [  3 292 275 278]
 [  4 278 275 259]
 [  5 278 259 262]]
[[617 346 345]
 [618 345 343]
 [619 343 340]
 [620 340 338]
 [621 338 333]]
[[685  11  12]
 [686  11   0]
 [687 348 346]
 [688 346 347]]
[[689   1  11]
 [690 346 332]]


In [25]:
print(coordinates[:10][:,0])
print(membrane[:10][:,0])
print(edge[:10][:,0])
print(support[:10][:,0])
print(truss[:10][:,0])        

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 1  2  3  4  5  6  7  8  9 10]
[617 618 619 620 621 622 623 624 625 626]
[685 686 687 688]
[689 690]


In [32]:
points = coordinates[:, 1:4] # spatial coordinates
 
triangles = membrane[:, 1:4]

faces = np.hstack([np.full((triangles.shape[0], 1), 3), triangles]).flatten()

In [ ]:
print(coordinates.shape)
print(points.shape)
print(faces.shape)

print(triangles.shape)


(349, 4)
(349, 3)
(2464,)
(616, 3)


In [ ]:
# np.hstack([np.full((5, 1), 3), triangles[:5]])

array([[  3, 346, 345, 344],
       [  3, 292, 290, 275],
       [  3, 292, 275, 278],
       [  3, 278, 275, 259],
       [  3, 278, 259, 262]])

In [ ]:
# [np.full((5, 1), 3), triangles[:5]]

[array([[3],
        [3],
        [3],
        [3],
        [3]]),
 array([[346, 345, 344],
        [292, 290, 275],
        [292, 275, 278],
        [278, 275, 259],
        [278, 259, 262]], dtype=int32)]

In [ ]:
# np.full((5, 1), 3)

array([[3],
       [3],
       [3],
       [3],
       [3]])

In [23]:
membrane_mesh = pv.PolyData(points, faces=faces)

In [24]:
edge_coo = edge[:, 1:3]
line_cells_edge = np.hstack([np.full((edge_coo.shape[0], 1), 2), edge_coo]).flatten()

support_coo = support[:, 1:3]
line_cells_support = np.hstack([np.full((support_coo.shape[0], 1), 2), support_coo]).flatten()

truss_coo = truss[:, 1:3]
line_cells_truss = np.hstack([np.full((truss_coo.shape[0], 1), 2), truss_coo]).flatten()

In [25]:
edge_mesh = pv.PolyData(points, lines=line_cells_edge)
support_mesh = pv.PolyData(points, lines=line_cells_support)
truss_mesh = pv.PolyData(points, lines=line_cells_truss)

In [ ]:
pl = pv.Plotter(notebook=False)
pl.add_mesh(membrane_mesh)
pl.add_mesh(edge_mesh,      line_width=2, color='darkred', label='Edges')
pl.add_mesh(support_mesh,   line_width=2, color='green', label='Supports')
pl.add_mesh(truss_mesh,     line_width=2, color='orange', label='Trusses')
pl.add_legend()
pl.show()
